logging:
  level:
    root: INFO
    com.thiagoti: DEBUG
server:
  port: ${SERVER_PORT:8181}
spring:
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:messagedb
    driverClassName: org.h2.Driver
    initialization-mode: always
  sql:
    init.mode: always
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  h2:
    console:
      enabled: false
      path: /messagedb
app:
  directory: C:\tmp
  whatsapp-bot:
    server: http://localhost:${WHATSAPP_BOT_SERVER_PORT:3100}